
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace ANN_Project
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            Console.WriteLine("Masukkan pesan yang berpotensi spam: ");
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Message = Console.ReadLine()
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("\nMelakukan prediksi dengan model untuk keputusan spam...");

            Console.WriteLine($"\nPrediksi IsSpam: {predictionResult.PredictedLabel}\n");
            Console.WriteLine("=============== Program selesai, tekan tombol apapun untuk Exit ===============");
            Console.ReadKey();
        }
    }
}
